# Generated by Django 4.2.8 on 2025-03-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tag', models.BooleanField(default=False)),
                ('meta_desc_found', models.BooleanField(default=False)),
                ('heading_tags_found', models.CharField(max_length=255)),
                ('keyword_page_frequency', models.IntegerField(verbose_name=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('site_name', models.TextField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_keyword', models.CharField(max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_Result_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.audit_result')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='audit_result',
            name='audit_notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.notes'),
        ),
        migrations.AddField(
            model_name='audit_result',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.user'),
        ),
        migrations.AddField(
            model_name='audit_result',
            name='website_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hootboostapi.website'),
        ),
    ]
