# Generated by Django 4.2.8 on 2025-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hootboostapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='target_keyword',
            field=models.CharField(max_length=10),
        ),
    ]
